// src/components/Footer.vue
<template>
  <footer>
    <img src="/assets/donut_badge.png" />
    <a href="https://riverside.rocks" target="_blank">
      <img src="/assets/rr_badge.png" />
    </a><br />
    <a href="https://rajeshtherobot.khaleelgibran.com/" target="_blank">hmmm</a>
    <iframe src='https://overengineering.kognise.dev/embed/khalby786' width='100%' height='100' style='user-select: none;' frameBorder='0'></iframe>
  </footer>
</template>

<script>
export default {};
</script>

<style scoped>
a:hover {
  background-color: inherit;
}

iframe {
  margin-top: 50px;
}
</style>

// src/components/Footer.svelte
<img src="/donut_badge.png" alt="Khaleel Gibran Donut Badge" class="inline-block mr-2 mt-6" />
<a href="https://riverside.rocks" target="_blank" class="inline-block align-middle mt-6">
  <img src="/rr_badge.png" alt="RiversideRocks Badge" />
</a>

<p class="text-slate-400 mt-10 text-sm">Edit <a href="https://github.com/khalby786/khaleelgibran.com" target="_blank">this page</a> and <a href="https://github.com/khalby786/" target="_blank">others on GitHub</a>.</p>

<footer class="mt-5 border border-b-0 border-l-0 border-r-0 border-slate-600">
  <p class="text-sm text-slate-300 pt-2">
    Please do not write beyond this line.
  </p>
</footer>
